#!/bin/sh

# This file is part of the qed project (https://github.com/vivien/qed).
#
# Copyright (c) 2016-2017 Vivien Didelot
# Copyright (c) 2016-2017 Lionel Nicolas
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# exit on failure
set -e

# exit on unassigned variable
set -u

# define colors
RESTORE='\033[0m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
BLUE='\033[01;34m'

# define usage
usage() {
	echo "usage: $0 [-h] [-d DISTRIBUTION] [-i] [-l] [-r] [-b] [-p] [CMD ARGS]"
	echo
	echo "	-h	show this help message"
	echo "	-d	target distribution"
	echo "	-i	enter interactive mode"
	echo "	-b	force re-build of a local docker base image"
	echo "	-p	force pull of docker base image from registry"
	echo "	-r	remove all containers associated to current working directory"
	echo
	exit ${1:-0}
}

list() {
	echo "listing containers"
	# TODO
}

remove() {
	echo "removing containers"
	# TODO
}

run() {
	if [ -z "$*" ]; then
		usage 2
	fi

	if ${rebuild}; then
		if [ -f ".qed/dockerfile.${distribution}" ]; then
			docker build \
				--tag ${project}-${distribution} \
				--file .qed/dockerfile.${distribution} \
				.qed/
		fi

	elif ${pull}; then
		docker pull ${distribution}
		docker tag ${distribution} ${project}-${distribution}
	fi

	echo "running command '$@' within ${distribution}"
	exec docker run \
		--rm \
		${interactive} \
		--volume ${PWD}:${PWD} \
		--workdir ${PWD} \
		--user `id -u`:`id -g` \
		${project}-${distribution} \
		$@
}

# default values
distribution=default
curdir=${PWD}
project=$(basename ${PWD})
interactive=
rebuild=false
pull=false
list=false
remove=false
action=run

# parse parameters
while getopts "hd:ilrbp" opt; do
	case $opt in
		h) usage 0 ;;
		d) distribution="${OPTARG}" ;;
		i) interactive="--interactive --tty" ;;
		b) rebuild=true ;;
		p) pull=true ;;
		l) action=list ;;
		r) action=remove ;;
		*) usage 1;;
	esac
done

shift "$((OPTIND-1))"

# check action
case ${action} in
	list|remove|run)
		${action} $@;;
	
	*)
		usage 3 ;;
esac
